spring.application.name=paymentservice
spring.datasource.url=jdbc:postgresql://localhost:5432/payments
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.redis.host=localhost
spring.data.redis.port=6379