services:
  payment-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payments
    ports:
      - "5432:5432"

  fraud-db:
    image: mongo:latest
    ports:
      - "27017:27017"

  velocity-cache:
    image: redis:latest
    ports:
      - "6379:6379"