_format_version: "3.0"
services:
 - name: payment-service
    url: http://payment-service:8082
    routes:
      - name: payment-route
        paths:
          - /api/payment
  - name: fraud-engine
    url: http://fraud-engine:8083
    routes:
      - name: fraud-route
        paths:
          - /api/fraud

plugins:
  - name: jwt
    config:
    uri_param_names:
      - jwt
    claims_to_verify:
      - exp
  - name: rate-limiting
    config:
      minute: 100
      policy: local
  - name: http-log
    config:
      http_endpoint: http://splunk:8088/services/collector/raw
      method: POST
      timeout: 10000
      keepalive: 60000
      headers:
        Authorization: "Splunk changeme"